<?php

/**
 * Public "Courses" catalog for Brainova School.
 * Covers: STEM & computing · Mathematics · Languages · Life skills.
 * Swap `image` URLs to uploads on your CDN when preferred (keep https).
 */
return [
    'hero' => [
        'title'       => 'Programs built for curiosity and confidence',
        'subtitle'    => 'Brainova combines nurturing care with AI-assisted, interactive learning paths. Explore age-right courses in STEM, literacy, maths, languages, and leadership—each with clear outcomes and educator support.',
        'primary_cta' => [
            'label' => 'Talk to admissions',
            'route' => 'frontend.contact',
        ],
        'secondary_cta' => [
            'label' => 'Start online admission',
            'route' => 'frontend.online-admission',
        ],
    ],

    'categories' => [
        ['slug' => 'all', 'label' => 'All programs'],
        ['slug' => 'stem', 'label' => 'STEM & computing'],
        ['slug' => 'math', 'label' => 'Mathematics'],
        ['slug' => 'language', 'label' => 'Languages'],
        ['slug' => 'skills', 'label' => 'Life skills'],
    ],

    'courses' => [
        [
            'slug'          => 'brainova-stem-discovery',
            'category'      => 'stem',
            'badge'         => 'STEM',
            'title'         => 'Brainova STEM Discovery Lab',
            'description'   => 'Hands-on introductions to computational thinking, simple robotics concepts, and safe digital workspaces—paired with playful design challenges.',
            'age_range'     => 'Ages 7–10',
            'grade'         => 'Grade 3–5',
            'lessons'       => '48 sessions',
            'duration'      => '4–6 months',
            'enrolled'      => 'Ongoing cohorts across sections',
            'accent'        => 'indigo',
            'image'         => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'STEM Discovery Lab at Brainova School: robotics concepts, computational thinking, and creative digital projects for Grades 3–5.',
            'overview'      => [
                'Learners rotate through guided “missions”: pattern games, Blockly-style logic, unplugged sequencing, and a gentle capstone where they pitch a tiny invention to classmates.',
                'Every unit links to formative checkpoints so families see skill growth—not just finished files. Sessions balance screen time with collaborative builds and mentor feedback.',
            ],
            'highlights' => [
                'Small groups with differentiated pathways',
                'Classroom-ready portfolio pieces (animations, puzzles, prototypes)',
                'Digital citizenship and consent-forward tool use woven into each sprint',
                'Optional weekend maker workshops when offered',
            ],
            'format' => 'Weekly 90-minute blocks + async practice snippets in the learner portal.',
        ],
        [
            'slug'          => 'brainova-ai-digital-literacy',
            'category'      => 'stem',
            'badge'         => 'AI & ethics',
            'title'         => 'Brainova AI Literacy & Guided Projects',
            'description'   => 'Responsible use of assistants and creative generators: learners ship short games, narratives, and data stories while learning how models work at a conceptual level.',
            'age_range'     => 'Ages 11–14',
            'grade'         => 'Grade 6–8',
            'lessons'       => '36 deep dives + studios',
            'duration'      => 'Two semesters',
            'enrolled'      => 'Rolling intake each term',
            'accent'        => 'violet',
            'image'         => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Middle-school AI literacy at Brainova: ethical use, prompting practice, and project studios with educator oversight.',
            'overview'      => [
                'Students practise “inspect, revise, cite” workflows: every AI-assisted artifact includes a learner reflection and attribution trail.',
                'Capstone cycles pair a creative build (interactive fiction, infographic series, lightweight web toy) with a peer review modeled on professional design critiques.',
            ],
            'highlights' => [
                'Guardian-visible activity summaries via the LMS',
                'No unsupervised vendor accounts—school-managed environments only',
                'Cross-curricular tie-ins with English and Humanities when scheduled',
                'Optional maths-of-AI teaser module for STEM-focused learners',
            ],
            'format' => 'Hybrid-friendly: two live facilitated blocks weekly plus coached async labs.',
        ],
        [
            'slug'          => 'brainova-math-confidence-pathway',
            'category'      => 'math',
            'badge'         => 'Mathematics',
            'title'         => 'Brainova Mathematics Confidence Pathway',
            'description'   => 'Number sense, word problems, and visual models that rebuild self-belief. Pacing adjusts after short diagnostics—never a one-size lecture hall.',
            'age_range'     => 'Ages 8–12',
            'grade'         => 'Grade 4–6',
            'lessons'       => '60 workshops',
            'duration'      => 'Academic year',
            'enrolled'      => 'Family info sessions each quarter',
            'accent'        => 'teal',
            'image'         => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Brainova maths pathway for upper primary: diagnostics, reasoning routines, and confidence-first teaching.',
            'overview'      => [
                'We alternate concrete manipulatives, pictorial anchors, and abstract notation so learners recognise when a tactic fits a new context.',
                'Problem strings and “estimate-then-verify” drills reduce anxiety around exams while keeping fluency gains honest and measurable.',
            ],
            'highlights' => [
                'Growth dashboards shared with guardians',
                'Intervention bursts for learners who plateau mid-year',
                'Calculator policy aligned with Cambridge / local syllabus expectations',
                'STEM fair tie-in option for modelling projects',
            ],
            'format' => 'Typically 3 × 55-minute encounters weekly + short retrieval homework sets.',
        ],
        [
            'slug'          => 'brainova-math-competition-studio',
            'category'      => 'math',
            'badge'         => 'Math+',
            'title'         => 'Brainova Competition Mathematics Studio',
            'description'   => 'For students who relish puzzles: contest-style problems, structured proof intuition, and time-boxed strategy rehearsals without burning out curiosity.',
            'age_range'     => 'Ages 11–15',
            'grade'         => 'Grade 7–9',
            'lessons'       => '54 challenges',
            'duration'      => '9-month arc',
            'enrolled'      => 'Interview or teacher referral',
            'accent'        => 'ocean',
            'image'         => 'https://images.unsplash.com/photo-1509228468518-fe40e0506024?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Competition mathematics studio at Brainova: Olympiad-flavoured training with wellbeing guardrails.',
            'overview'      => [
                'Learners dissect classic themes—invariants, bijections, clever counting—in weekly “sprints” followed by communal solution autopsies.',
                'We deliberately cap weekly workload to avoid overtraining; mindfulness and sleep hygiene checkpoints are explicit family touchpoints.',
            ],
            'highlights' => [
                'Mentors with regional contest backgrounds',
                'Mock paper weekends with humane feedback rubrics',
                'Cross-link to Physics / CS problem aesthetics when cohort interest spikes',
                'Scholarship conversations for nationals-bound candidates',
            ],
            'format' => 'Invitation-only sectional + Sunday deep-work lab (timing adjusted per Ramadan calendars when applicable).',
        ],
        [
            'slug'          => 'brainova-english-communication-studio',
            'category'      => 'language',
            'badge'         => 'English',
            'title'         => 'Brainova English Communication Studio',
            'description'   => 'Close reading, academic writing frameworks, vocabulary layers, and low-stakes speaking reps—toward articulate, organised expression in English.',
            'age_range'     => 'Ages 10–14',
            'grade'         => 'Grade 5–8',
            'lessons'       => '40 coaching cycles',
            'duration'      => 'Year-long / term modules',
            'enrolled'      => 'Assessment-led placement bands',
            'accent'        => 'amber',
            'image'         => 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'English studio at Brainova: reading comprehension, structured writing, and confident speaking cycles.',
            'overview'      => [
                'Each six-week arc moves from mentor model texts → scaffolded imitation → learner-authored artefacts with conferencing notes.',
                'Speaking loops include parliamentary phrasing for shy contributors and extension pathways for debating society hopefuls.',
            ],
            'highlights' => [
                'Annotated exemplars keyed to syllabus descriptor bands',
                'Peer review protocols that emphasise specificity and kindness',
                'Optional bilingual glossaries co-built with Humanities',
                'Parent viewing nights showcasing portfolio growth',
            ],
            'format' => 'Mixed whole-group mini-lessons and rotating writing conferences.',
        ],
        [
            'slug'          => 'brainova-biliteracy-foundations',
            'category'      => 'language',
            'badge'         => 'Languages',
            'title'         => 'Brainova Biliteracy Foundations',
            'description'   => 'Structured pathway for strengthening home/school languages (e.g., Arabic literacy circles or Urdu story labs) beside English—with cultural projects, not drills alone.',
            'age_range'     => 'Ages 9–13',
            'grade'         => 'Grade 4–7',
            'lessons'       => '44 immersive blocks',
            'duration'      => 'Two consecutive terms minimum',
            'enrolled'      => 'Dialect-sensitive cohort grouping',
            'accent'        => 'rose',
            'image'         => 'https://images.unsplash.com/photo-1524998497720-b78e62e88b48?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Biliteracy foundations supporting Arabic/Urdu and English interplay at Brainova School.',
            'overview'      => [
                'We foreground authentic texts—poetry excerpts, diaspora narratives, news bytes tailored for minors—paired with morphology warm-ups caregivers can reinforce.',
                'Oral competency is tracked alongside script fluency so heritage speakers feel honoured, while newcomers get transparent stepping stones.',
            ],
            'highlights' => [
                'Rotation of native-speaking facilitators alongside English-medium coaches',
                'Cross-grade pen-pal swaps with moderated safety rules',
                'Heritage learner identity workshops each semester',
                'Optional translanguaging reflections in learner journals',
            ],
            'format' => 'Mostly onsite circle time + selective voice-note homework for pronunciation loops.',
        ],
        [
            'slug'          => 'brainova-leadership-voice-studio',
            'category'      => 'skills',
            'badge'         => 'Leadership',
            'title'         => 'Brainova Leadership & Voice Studio',
            'description'   => 'Public narration, persuasive structure, moderated debates, and “calm-under-spotlight” drills that translate to assemblies, councils, and later interviews.',
            'age_range'     => 'Ages 11–16',
            'grade'         => 'Grade 6–10',
            'lessons'       => '32 performance labs',
            'duration'      => 'Half-year sprint or full-year depth',
            'enrolled'      => 'Limited seats per voice coach ratio',
            'accent'        => 'coral',
            'image'         => 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Leadership and public speaking studio: debates, narratives, and composure coaching at Brainova.',
            'overview'      => [
                'Learners practise micro-stories before macro speeches; camera-aware feedback loops build media literacy simultaneously.',
                'Student parliament simulations teach procedural fairness—useful beyond any single speech contest.',
            ],
            'highlights' => [
                'Coach-curated warmup rituals for physiological regulation',
                'Accessibility accommodations for stutter/anxiety disclosures',
                'Inter-school friendly scrimmages when partnerships allow',
                'Recorded exemplar library families can revisit',
            ],
            'format' => 'Primarily onsite with occasional broadcast-style studio days.',
        ],
        [
            'slug'          => 'brainova-future-projects-lab',
            'category'      => 'skills',
            'badge'         => 'Innovation',
            'title'         => 'Brainova Future Projects Lab',
            'description'   => 'Design-thinking sprints where teams interview users, prototype services, pitch investors (played by alumni), and reflect on feasibility—not fantasy pitch decks.',
            'age_range'     => 'Ages 13–18',
            'grade'         => 'Grade 8–12',
            'lessons'       => '28 design cycles',
            'duration'      => 'Capstone-heavy term',
            'enrolled'      => 'Application + team charter',
            'accent'        => 'slate',
            'image'         => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Future Projects Lab: design thinking, entrepreneurship basics, and capstone pitches at Brainova.',
            'overview'      => [
                'Teams traverse empathy maps → assumption tests → clickable mockups → sustainable operations conversations (including safeguarding data).',
                'Equity critiques are baked in—every cohort runs an “impact on community” retrospective before demos.',
            ],
            'highlights' => [
                'Mentor office hours from local startup volunteers when available',
                'Ethical AI/product reviews for teens shipping digital MVPs',
                'Scholarship micro-grants for top community-positive ideas',
                'Credits toward service-learning requirements where applicable',
            ],
            'format' => 'Immersive project blocks alternating with mentorship panels.',
        ],
    ],

    'faqs' => [
        [
            'q' => 'Which program should we start with?',
            'a' => 'Share your child’s grade band and weekly bandwidth; admissions routes you to diagnostics (maths/English/biliteracy) or straight enroll when placements are obvious.',
        ],
        [
            'q' => 'How does Brainova use AI responsibly in class?',
            'a' => 'Assistants run in supervised contexts. Learners annotate outputs, teachers model verification habits, and guardian summaries highlight what happened—not just final scores.',
        ],
        [
            'q' => 'Are courses only on campus?',
            'a' => 'Most labs are face-to-face for younger cohorts. Middle and upper programs may blend live sessions with portal tasks—exact mix is published per intake letter.',
        ],
        [
            'q' => 'Fees, scholarships, and payment plans?',
            'a' => 'Contact admissions or complete the online admission flow; counselors share the current fee grid, sibling policies, and any term-limited bursaries.',
        ],
    ],

    'trust' => [
        'headline' => 'Why families choose Brainova programs',
        'body'     => 'Experienced mentors, transparent reporting, and a culture that treats technology as a tutor—not a replacement for relationships. Your child progresses with adults who notice both effort and mastery.',
    ],
];
